ble_monitor:
  bt_interface: !secret ble_monitor_bt_interface_builtin
  discovery: false
  restore_state: true
  decimals: 1
  period: 300
  devices:
    - name: Living Room Thermo
      mac: !secret living_room_thermo_mac
      encryption_key: !secret living_room_thermo_mi_bind_key
    - name: Living Room Flower Care
      mac: !secret living_room_flower_care_mac

input_boolean:
  settings_ble_gateway:
    name: BLE Gateway
    icon: mdi:bluetooth
  settings_ble_gateway_discovery:
    name: BLE Gateway Discovery
    icon: mdi:bluetooth-connect

input_text:
  settings_ble_gateway_add_device:
    name: BLE Gateway Add Device
    icon: mdi:bluetooth-connect
    initial: ''

automation:
  - alias: ESPHome BLE Advertise
    mode: queued
    trigger:
      - platform: event
        event_type: esphome.on_ble_advertise
    action:
      - service: ble_monitor.parse_data
        data:
          packet: "{{ trigger.event.data.packet }}"
          gateway_id: "{{ trigger.event.data.gateway_id if trigger.event.data.gateway_id is defined else 'unknown' }}"

template:
  - binary_sensor:
      - name: BLE Gateway
        icon: mdi:bluetooth
        state: "{{ is_state('input_boolean.settings_ble_gateway', 'on') }}"
        attributes:
          discovery: "{{ is_state('input_boolean.settings_ble_gateway_discovery', 'on') }}"
          devices: >-
            {% set ns = namespace(items = []) %}
            {% for entity_id in integration_entities('ble_monitor') | select('match', '^(device_tracker|sensor)\.') | map('device_id') | unique %}
              {% for ident in device_attr(entity_id, 'identifiers') %}
                {% if ':' in ident[1] %}
                  {% set ns.items = ns.items + [ident[1]] %}
                {% endif %}
              {% endfor %}
            {% endfor %}
            {{ (ns.items | unique | sort | join('') | replace(':', '')) ~ (states('input_text.settings_ble_gateway_add_device') | replace(':', '') | trim) if is_state('binary_sensor.ble_gateway', 'on') }}
